### ISSUE TITLE
Add flag to attach to all available kernel modules

### ISSUE THREAD

**Issue by lbernail** [cilium/pwru#100]
We can do this today with
```--kmods $(ls /sys/kernel/btf/ | grep -v vmlinux | tr '\n' , | sed 's/.$//')```

A `--all-kmods` flag would be nice

**Comment by varunkumare99** [comment]
Hi
I'm new to ebpf and pwru.
I would like to work on this.
Any idea on how to begin?
Thanks

**Comment by brb** [comment]
@varunkumare99 :wave: This would require adding a new flag, and then passing all kernel module names from `/sys/kernel/btf/` to the `GetFuncs()` function. No eBPF knowledge is required. Please let me know if you are willing to work on this, so that I can assign the issue to you.

**Comment by varunkumare99** [comment]
Yes, I'm willing to work on this.

**Comment by varunkumare99** [comment]
I'm unable to run pwru with docker.

> sudo docker run --privileged --rm -t --pid=host -v /sys/kernel/debug/tracing:/sys/kernel/debug/tracing cilium/pwru --filter-dst-ip=1.1.1.1

`docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/sys/kernel/debug/tracing" to rootfs at "/sys/kernel/debug/tracing": mkdir /var/lib/docker/overlay2/c1572db5282c23f07099badddd4e2eabdc3afddc21f8ebd42be43faf357cd635/merged/sys/kernel/debug/tracing: no such file or directory: unknown.`

**Comment by brb** [comment]
For posterity, the fix was to run with:
```
sudo docker run --privileged --rm -t --pid=host -v /sys/kernel/debug/:/sys/kernel/debug/ cilium/pwru --filter-dst-ip=1.1.1.1
```

**Comment by varunkumare99** [comment]
thanks I'm able to run it now.

**Comment by varunkumare99** [comment]
I have raised a PR : #109
