### ISSUE TITLE
Enable kprobe-multi backend for kernel modules tracing (--kmods)

### ISSUE THREAD

**Issue by brb** [cilium/pwru#147]

**Comment by rgo3** [comment]
I'd be interested to work on this as my first contribution to pwru, any pointers to where I should start would be helpful 🙏

**Comment by brb** [comment]
Thanks!

This commit https://github.com/cilium/pwru/commit/820fbb26 has some pointers why we did not enable the kprobe-multi backend when used with `--kmods`. IIRC [the kernel fix](https://lore.kernel.org/bpf/20221025134148.3300700-1-jolsa@kernel.org/) should have been merged and backported.

You could try the following:
1. Drop the kmod check from https://github.com/cilium/pwru/blob/v1.0.9/main.go#L91
2. Troubleshoot if there are any ignored attachments when starting pwru (reporting as `Attached (ignored X)`). kmods might be not visible in `available_filter_functions` (https://github.com/cilium/pwru/blob/v1.0.9/internal/pwru/utils.go#L27), so more conditions might need to be relaxed.
