### ISSUE TITLE
pwru fails to run if compiled on machine with more CPUs than target

### ISSUE THREAD

**Issue by terinjokes** [cilium/pwru#183]
If the machine that compiled pwru has more CPUs than the machine that runs it I get the following error, along with an exit code 1:

```
Creating perf event reader: failed to create perf ring for CPU 1: can't create perf event: Invalid argument
```

I've attached the full strace, but the main syscall that failed is installing the perf_event to the (non-existent) second CPU:

```
[pid  1994] perf_event_open({type=PERF_TYPE_SOFTWARE, size=PERF_ATTR_SIZE_VER7, config=PERF_COUNT_SW_BPF_OUTPUT, sample_period=0, sample_type=PERF_SAMPLE_RAW, read_format=0, watermark=1, precise_ip=0 /* arbitrary skid */, ...}, -1, 1, -1, PERF_FLAG_FD_CLOEXEC) = -1 EINVAL (Invalid argument)
```

[strace.log](https://github.com/cilium/pwru/files/11602125/strace.log)

---

Previously discussed in https://github.com/cilium/pwru/issues/89#issuecomment-1563044780

**Comment by brb** [comment]
Thanks for the issue! @ti-mo MBOI.

**Comment by terinjokes** [comment]
Closing, as this turned out to be a packaging mistake.
