### ISSUE TITLE
Track SKB clones

### ISSUE THREAD

**Issue by brb** [cilium/pwru#200]
@borkmann suggested to extend the SKB tracking introduced in https://github.com/cilium/pwru/pull/194 with:

> it would be nice to have a --follow-skb-clones option where we add new addresses to that tracker map whenever there was a clone or copy of the skb in order to get visibility where their paths go.

**Comment by Asphaltt** [comment]
With `--filter-track-skb` option, I think it's easy to track the skb clones by kprobing `__skb_clone()` (not kretprobing `skb_clone()`):

```C
SEC("kprobe/__skb_clone")
int kprobe___skb_clone(struct pt_regs *ctx) {
	u64 n = (u64) PT_REGS_PARM1(ctx);
	u64 skb = (u64) PT_REGS_PARM2(ctx);
	bool *v;

	if (cfg->track_skb) {
		v = bpf_map_lookup_elem(&skb_addresses, &skb);
		if (v)
			bpf_map_update_elem(&skb_addresses, &n, &TRUE, BPF_ANY);
	}

	return 0;
}
```

Some info about `skb_clone()`:

```bash
# bpftrace -l 'k:*skb_clone'
kprobe:__skb_clone
kprobe:skb_clone
```

Source code of `__skb_clone()`:

https://elixir.bootlin.com/linux/v6.5.7/source/net/core/skbuff.c#L1377

**Comment by brb** [comment]
@Asphaltt That's a good idea! And then kretprobe for `skb_copy()` - https://elixir.bootlin.com/linux/v6.5.7/source/net/core/skbuff.c#L1927.

**Comment by Asphaltt** [comment]
It seems kretprobing `skb_clone()` is better, Because `__sk_clone()` is called by `skb_morph()` too.

Finally, with `--filter-track-skb` option, kretprobing `skb_clone()` and `skb_copy()` is the accurate solution to track skb clones.

**Comment by Asphaltt** [comment]
But, I don't like kretprobing because we cannot get the skb argument at the same time.

Maybe, the following solution is better:
1. kprobe `skb_clone()` and `__skb_clone()`, then track skb in kprobing `__skb_clone()`.
2. kprobe `skb_copy()` and `skb_copy_header()`, then track skb in kprobe `skb_copy_header()`.

**Comment by brb** [comment]
> But, I don't like kretprobing because we cannot get the skb argument at the same time.

Could we use `fexit` instead? AFAIK it has access to args.

**Comment by Asphaltt** [comment]
Yes, `fexit` is better. But 5.4 kernel does not support it.

So, I think, kprobing just `__skb_clone()` and `skb_copy_header()` is OK, no matter who calls them.
