### ISSUE TITLE
support filter by net namespace

### ISSUE THREAD

**Issue by duanjiong** [cilium/pwru#23]
Network addresses may overlap between multiple net namespaces, which can interfere with our filtering.

**Comment by Asphaltt** [comment]
> assign netns ID to an existing netns to facilitate your proposed debugging?

By looking down the kernel source code [net_namespace/peernet2id](https://elixir.bootlin.com/linux/v5.15.3/source/net/core/net_namespace.c#L267), **netnsid** is not retrieved from `struct net` neither `struct ns_common`.

**inode** is a good way to identify an net namespace. In kernel space, inode is the `unsigned int inum` field of `struct ns_common`. In user space, inode is the inode of the net namespace file, wherever the file is, like `/proc/<pid>/ns/net`, `/var/run/docker/netns/<netns name>`.

For example:

log of pwru: *0xffff8f26c23d4500 [isc-worker0000]     neigh_resolve_output    3355665098061 netns=4026531992 mark=0x0 ifindex=2 proto=8 mtu=1500 len=62*

inode of netns file: *got netns: NS(4:4026531992)* 

(Go code to get inode: [ns.UniqueID](https://github.com/vishvananda/netns/blob/50045581ed74/netns.go#L52))

**Comment by brb** [comment]
@Asphaltt Thanks! Using the inode makes sense to me. Would you like to work on this?

**Comment by brb** [comment]
Fixed by #34.
