### ISSUE TITLE
Would be nice if probe unloading was faster

### ISSUE THREAD

**Issue by deliciouslytyped** [cilium/pwru#274]
Thank you so much for writing this awesome tool, it has made learning, using, and debugging the Linux network stack not just so much easier, but feasible at all for me. I used to have so much trouble figuring out why something wasn't working. (Significant kudos to kernel devs as well for enabling this with probing functionality.)

Is there any way to make attaching and detaching probes faster? Detaching probes seems to go a few times slower than attaching for me.

I guess maybe https://github.com/cilium/pwru/pull/99 isn't implemented for unloading?

**Comment by brb** [comment]
Thanks for the issue (and feedback)!

Could you provide the following?
- Which kernel (`uname -a`)
- Params for `pwru`
- The first log lines before `Listening for events`

**Comment by Asphaltt** [comment]
Why not attaching/detaching kprobes concurrently?

It seems better to attach/detach kprobes concurrently.

```bash
./pwru --backend kprobe --output-meta --output-tuple icmp
2023/10/23 13:01:12 Attaching kprobes (via kprobe)...
1462 / 1462 [----------------------------------------------------------------------------------------------------] 100.00% 347 p/s
2023/10/23 13:01:17 Attached (ignored 0)
2023/10/23 13:01:17 Listening for events..
               SKB    CPU          PROCESS                     FUNC
^C2023/10/23 13:01:19 Received signal, exiting program..
2023/10/23 13:01:19 Detaching kprobes...
215 / 1462 [--------------->_______________________________________________________________________________________] 14.71% 35 p/s
```

P.S. it seems something wrong with the progressbar.

**Comment by deliciouslytyped** [comment]
Cool!

I haven't tested, but it looks like detach is still an order of magnitude (p/s) slower? (This is not significant for my usecase.)

**Comment by Asphaltt** [comment]
> I think we could detach in batches too.

It does detach in batches: [DetachKprobes()](https://github.com/cilium/pwru/blob/main/internal/pwru/kprobe.go#L117)

**Comment by brb** [comment]
Oops, my bad.
