### ISSUE TITLE
Support for Openshift 4.12/13?

### ISSUE THREAD

**Issue by slmingol** [cilium/pwru#342]
Was curious to try this on OCP4.12/13 which includes the following Linux kernel:

```
sh-4.4# uname -a
Linux app1-6hpk5-worker-t47bn 4.18.0-372.71.1.el8_6.x86_64 #1 SMP Fri Aug 25 08:34:17 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
sh-4.4# cat /etc/redhat-release
Red Hat Enterprise Linux CoreOS release 4.12
sh-4.4#
```

I've seen the required versions stated in the README but know historically Redhat has backported quite a bit of functionality from newer Linux kernels to RH's version. Would this particular version of RH's kernel be supported?

**Comment by brb** [comment]
That RHEL kernel should have all required backports. I'd suggest to give it a go. If anything is missing, you will see an error when running `pwru`.
