### ISSUE TITLE
Getting errors

### ISSUE THREAD

**Issue by sripor62** [cilium/pwru#361]
./main.go:124:18: undefined: LoadKProbeMultiPWRU
./main.go:126:18: undefined: LoadKProbePWRU
./main.go:128:18: undefined: LoadKProbeMultiPWRUWithoutOutputSKB
./main.go:130:18: undefined: LoadKProbePWRUWithoutOutputSKB

I am getting these errors.Is there a way to resolve these?

**Comment by brb** [comment]
How did you install pwru? If compiling yourself, please run `make clean && make`.
