### ISSUE TITLE
 invalid go version '1.21.0': must match format 1.23

### ISSUE THREAD

**Issue by ftasnetamot** [cilium/pwru#382]
When trying to compile pwru un a current linux system I receive this weird error message:
Its asking for a future version of golang. When [Looking to all go releases](https://go.dev/dl/)  1.22.3 ist the most current go version.

```
TARGET_GOARCH=amd64 go generate
go: errors parsing go.mod:
/home/user/pwru/go.mod:3: invalid go version '1.21.0': must match format 1.23
/home/user/pwru/go.mod:5: unknown directive: toolchain
make: *** [Makefile:20: pwru] Fehler 1
```

Edit: My go version is  go1.19.8.  Line 3 of /home/user/pwru/go.mod is:  `go 1.21.0`

Can it be, that your [Dependacy ](https://github.com/cilium/pwru?tab=readme-ov-file#dependencies) 1.16 is not longer up to date?

**Comment by brb** [comment]
Could you try upgrading your Go? It compiles on my machine with `go version go1.22.2 linux/amd64`
