### ISSUE TITLE
no tcp flags ,such as  syn, fin,ack  info   when exec   ./pwru 'port 22 '     --output-tuple  --output-meta           --output-limit-lines 10  

### ISSUE THREAD

**Issue by sjaliang** [cilium/pwru#417]
![image](https://github.com/user-attachments/assets/0176f280-077f-4653-b7f7-746168bd10e6)

**Comment by brb** [comment]
Thanks for the issue. `pwru` when outputting does not show any TCP flags. We could consider accepting a PR which extends it.
