### ISSUE TITLE
Packet rerouting, v/s forwarding, v/s switching, v/s redirecting

### ISSUE THREAD

**Issue by arayu05** [cilium/pwru#42]
Hi Team,
I have a very basic question. As I've seen everywhere people are using different terms while using ebpf for packets journey.
Can someone please explain the difference b/w below terms when we write ebpf code :

Packet rerouting,
Packet forwarding,
Packet switching,
Packet redirecting

**Comment by brb** [comment]
Hi @arayu05, I'm not sure how this question is relevant to this repository. Closing.
