### ISSUE TITLE
libpcap filtering is broken for XDP (--filter-trace-xdp)

### ISSUE THREAD

**Issue by brb** [cilium/pwru#438]
Any libpcap filter seems to be ignored when using with `--filter-trace-xdp`. git-bisect points to https://github.com/cilium/pwru/commit/0dc98291c680e9a5935ed84f93d904c7f16528f8 (cc @Asphaltt )

**Comment by Asphaltt** [comment]
I don't believe that the commit 0dc98291c680e9a5935ed84f93d904c7f16528f8 is responsible for breaking the `pcap-filter` + `--filter-trace-xdp` functionality, as the issue persists even with commit 1de15ffe7b50c8897ef0e5f981099b879dc2e08b. 

In fact, `--filter-trace-xdp` was already broken before the 1de15ffe7b50c8897ef0e5f981099b879dc2e08b commit. As a result, it’s difficult to pinpoint exactly which commit caused the issue with `pcap-filter` + `--filter-trace-xdp`.

**Comment by Asphaltt** [comment]
After investigating the commit history manually alongside this diff [pwru-trace-xdp.txt](https://github.com/user-attachments/files/17381049/pwru-trace-xdp.txt), I confirm the commit 2893168ca887a7a8a86131dfa51043b67aeacfde  is responsible for breaking the functionality. Then, when revert the commit, it works expectedly.

@jschwinger233 can you do more investigation?

**Comment by brb** [comment]
Thanks for the investigation! I think the last if-statement's condition needs to be changed to "if (!filter(...)) { return ...}".

**Comment by Asphaltt** [comment]
>  the last if-statement's condition needs to be changed to "if (!filter(...)) { return ...}".

Indeed.
