### ISSUE TITLE
Print packet drop reason collected from `kfree_skb_reason`

### ISSUE THREAD

**Issue by aditighag** [cilium/pwru#54]
Details are in the lwn article - https://lwn.net/Articles/885729/.

>This information is not actually useful to the kernel, but it has been added to the existing kfree_skb tracepoint, making it available to any program that connects to that tracepoint.

It looks like the drop reasons are available with the existing trace point.

**Comment by brb** [comment]
I've looked into this. Unfortunately, currently not many drops are wrapped with `kfree_skb_reason` - https://elixir.bootlin.com/linux/latest/A/ident/kfree_skb_reason.
