### ISSUE TITLE
Switch from brb/ebpf (fork) to cilium/ebpf

### ISSUE THREAD

**Issue by brb** [cilium/pwru#8]
This requires the following in cilium/ebpf:
- Exposing `internal/btf` package.
- Implementing iterator.

See https://github.com/brb/ebpf/tree/pwru for the diff.

**Comment by tklauser** [comment]
> This requires the following in cilium/ebpf:
> 
> * Exposing `internal/btf` package.

It seems the `btf` package was recently exported: https://github.com/cilium/ebpf/pull/665

> * Implementing iterator.

So I think the missing `Iterate` method (or whatever the cilium/ebpf maintainers deem appropriate) is all that's missing to switch to cilium/ebpf.

**Comment by brb** [comment]
Aye, I am planning to add a getter for `namedTypes` instead of adding the `Iterate` method.

**Comment by brb** [comment]
The PR for the iterator is out - https://github.com/cilium/ebpf/pull/678.
