### ISSUE TITLE
Use multi-link kprobe attachment

### ISSUE THREAD

**Issue by brb** [cilium/pwru#87]
Once https://github.com/cilium/ebpf/pull/716 has been merged, we can start using the multi-link kprobes. This should significantly reduce the startup time.

**Comment by vincentmli** [comment]
I am interested in the multi-link kprobes, so good issue for me to learn, I will give it a try :)

**Comment by vincentmli** [comment]
Hi @brb, I have  questions, to update pwru to use `cilium/ebpf v0.9.2` which has multi-link kprobes merged, is it just update the go.mod and go.sum enough? and how do you get the info like the `<time-stamp>` and `<hash>`  in go.mod `v0.9.2-0.<time-stamp>-<hash>`

```
 github.com/cilium/ebpf v0.9.1-0.20220705115408-426053e5393e
```
also how do get the go.sum like

```
github.com/cilium/ebpf v0.9.1-0.20220705115408-426053e5393e h1:zqo4hqEMEsGMi6P6JVi2eQA90LyYMAlRWMfBmIWZ0bc=
github.com/cilium/ebpf v0.9.1-0.20220705115408-426053e5393e/go.mod h1:+OhNOIXx/Fnu1IE8bJz2dzOA+VSfyTfdNUVdlQnxUFY=
```

**Comment by brb** [comment]
@vincentmli Thanks for taking care of this.

> is it just update the go.mod and go.sum enough

Please run `go get github.com/cilium/ebpf@v0.9.2` from the `pwru` dir - this should update `go.{mod,sum}` (don't forget to commit both).
